### ISSUE TITLE
Corriger le modèle sur les titre des LandingOptions

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1017]
On a à la fois `landing_option.title` et `landing_option.form_title`; `landing_option.title` n’est plus utilisé dans les pages, ni dans l’admin, mais est affiché dans /sollicitations; `landing_option.form_title` est affiché dans les pages et dans l’admin.

(`title` est une colonne, `form_title` est dans la colonne jsonb `content`. J’aurais tendance à supprimer title et passer à autre chose.)

**Comment by LucienMLD** [comment]
Si les LandingOption n'ont plus de titre on afficherait quoi dans /solicitations ? Par exemple une sollicitation a pour`title` ""Appui en cas de conflit avec votre banque (Banque de France)"  et `form_title`"Vous souhaitez être accompagné face au refus de votre banque de suspendre vos remboursements en cours ou de vous accorder un prêt de trésorerie." Ce n'est pas la même chose

**Comment by n-b** [comment]
En tout cas, LandingOption.title n’est pas modifiable dans l’admin, on a un problème :)

Pour toi ça serait pertinent d’avoir deux titres, un visible pour les entreprises, et un visible pour les conseillers et le support? Je comprends l‘intérêt, mais ça me chagrine un peu. J’aime bien que le produit soit “transparent“, que le fonctionnement ne soit pas “caché”. Avoir les mêmes titres, ça aide les conseillers à se mettre à la place des entreprises.
