### ISSUE TITLE
Améliorer le contenu des besoins créés à partir d'une sollicitation

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#1028]
On veut quoi pour ce genre de cas ?
Actuellement à l'étape "Détection des besoins" si on ajoute du texte dans "Plus d'infos sur ce besoin" ça rempli le contenu d'un besoin et ça crée un premier commentaire.
Si on prérempli le contenu avec le texte de la sollicitation le mécanisme sera le même on se retrouvera donc avec deux fois le même texte sur la page analyse, une fois dans l'encadré "sollicitation x" et une fois dans le premier commentaire.
On peut envisager que dans le cas ou une analyse est créé à partir d'une sollicitation on n’a pas de champs "Plus d'infos sur ce besoin" car on l'a déjà dans la sollicitation, et ça ne crée pas non plus de commentaire, la description de la sollicitation est déjà sur la page. L'inconvénient c'est qu'il n'y a pas de correction possible du texte de la sollicitation si le mec a écrit n'importe comment.

![imagea](https://user-images.githubusercontent.com/22002486/79957129-6ea24f80-8481-11ea-8b23-bb8ce05ebe2a.png)

![imagez](https://user-images.githubusercontent.com/22002486/79957134-7104a980-8481-11ea-890f-a0be71117b3f.png)

**Comment by n-b** [comment]
À vue de nez, il y a deux points indépendants:
* copier-coller le texte de la sollicitation dans la description du besoin, au besoin en citant avec des quillemets ou des `<blockquote>`. On peut faire ça dans DiagnosisCreation, c’est pas cher.
* inclure cette description dans le mail. Pour l’instant dans notify_company_needs, on indique le `needs.content` mais pas le `diagnosis.content`. cf aussi #968
