### ISSUE TITLE
Comptabiliser les affichages des formulaires en iframe

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#1074]

**Comment by LucienMLD** [comment]
Le code est présent en javascript, une partie des stats semble bloqué, peut être que certains navigateurs bloquent le javascript des iframes. Il n'y a pas de gem pour Matomo pour faire ça dans le back. Le moyen qui semble le plus efficace est de faire une requête http avec les paramètres qui vont bien.

**Comment by n-b** [comment]
En fait, j’ai l’impression que ça marche dans les configurations normales sur la plupart des navigateurs actuels. Safari loggue une erreur, mais je suppose que c’est une exception qui est catchée plus loin par matomo dans le code qui détecte la présence de l’iframe: en gros, le script essaie de voir l’url de la page, ce qu’il n’a pas le droit de faire, mais on s’en fiche parce que ce n’est pas ça qu’on compte.

D‘ailleurs l’affichage de la page lui-même est compté, je ne crois pas que l’évènement `affichage-formulaire-partenaire` soit utile.

**Comment by n-b** [comment]
Je ferme, ça marche.
