### ISSUE TITLE
Refaire la page stats

### ISSUE THREAD

**Issue by MathieuGens** [betagouv/place-des-entreprises#1088]
## STATS PUBLIQUES
(sur le portail)

Document de discussion actualisé : https://docs.google.com/document/d/1TqFwK0GGhyqTyXXCghB1JCnL98R6MIrEDr_36kSW6I8/edit

Anciennes discussions : 

Nos 3 métriques phares, simples et visibles:
- Nb d’entreprises aidées (ayant eu un besoin pris en charge ou résolu) - par région
- % satisfaction d’entreprise (précaution c'est une enquête téléphonique) 
- % de prise en charge des sollicitations dans les 7 jours [délai à préciser suite calcul/graphique]

## STATS INTERNES
(pour l’équipe)

### Qualité
(flux, référencement, service rendu)

filtrer par date 

- [x] Nb de besoins transmis - par région
- [x] % de sollicitations donnant des mises en relations
- [x] Répartition par thème (camembert)
- [ ] Répartition sectorielle d'activité
- [x] Répartition par tranches d'effectifs (réduire les tranches d’effectifs pour plus de visibilité)
- [ ] Nb de besoins en attente de positionnement (aucune prise en charge) -chiffre instant T
- [ ] Nb de besoins clôturés (dont 1 MER clôturé) (regarder avec le premier graph, redondance ?) 
- [ ] Nb de besoins archivés - par région 
- [ ] Faire remonter les données des relances (10 jours, 15jours...)
---
- [ ] Nb de besoins clôturés de manière optimale (toutes les réponses sur les MER) (au bout d'un certain temps)
- [ ] Délai de prise en charge des sollicitations (dans 90% des cas) [à préciser suite calcul/graphique]
- [ ] Nb d'experts qui n’ont pas pris en charge depuis 1 mois (onglet relance expert ?)
- [ ] temps moyen pour mettre en relation une sollicitation (<72h) 
- [ ] % de réattribution
- [ ] (% de sollicitations de mauvaise qualité ?)

###### Autres (à préciser / plus tard)

- Nb moyen d’experts qui prennent en charge un besoin (ni trop faible, ni trop fort et au regard du nb d'expert par sujet)
- % d’expert qui n’ont pas été notifié depuis 6 mois - déterminer la période avant perte de l'engagement de l'expert ?

### Suivi côté acquisition

- Nb de sollicitations au mois
- Evolution nb de sollicitations fonction des actions
- Taux de conversion par action
- Coût de la sollicitation par action
- % de sollicitations donnant des mises en relations au total
-Nb ets abonnées Newsletter (attention pas q des ets) 
-Nb de followers linkedin (si distinguo ets c'est mieux) 

###### Autres (à préciser / plus tard)

-% de sollicitations donnant des mises en relations par actions

## STATS POUR LES PARTENAIRES :

- 1er niveau décrit dans convention mais possible d’aller plus loin
- à compléter d’une vue qualitative sur l’activité de l’institution 
- pouvoir télécharger un CSV des besoins réceptionnés / de l'ensemble des besoins de la Région

Document pour discuter ensemble : https://docs.google.com/document/d/1pC3LVieR22M_gGUYlQNN99pWrbpsHYbjvnNGuH-YQa0/edit

**Comment by MathieuGens** [comment]
Une stat de plus : 
Le temps moyen pour mettre en relation une sollicitation (<72h)

**Comment by n-b** [comment]
Pour calculer le délai de prise en charge:
```
> times = Match.where.not(closed_at: nil)
  .group(:need_id)
  .minimum("EXTRACT(EPOCH FROM closed_at - created_at)")
  .values
=> […]
> distance_of_time_in_words(times.percentile(66))
=> "environ un mois"
```
(Il faut aussi implémenter [Array::percentile](https://github.com/thirtysixthspan/descriptive_statistics/blob/a54e313bb743a07fa3912c14486a55a1a8de8c17/lib/descriptive_statistics/percentile.rb).)

**Comment by MathieuGens** [comment]
Au regard de nos derniers échanges avec les partenaires/sponsors,
ils attendront plus de statistiques publiques directement "visibles".
On s'était trop restreint ? Bien articuler ensuite avec la possibilité de télécharger des données (l'activité stat sur la région, l'activité de mon institution).

Je pense que ces indicateurs doivent être publics :
- Répartition par thème
- Répartition sectorielle d'activité
- Répartition par tranches d'effectifs

Concernant,
- % satisfaction d’entreprise 
=> on a 2 questions : %de personnes rappelées par un expert ; %de solutions apportées satisfaisantes.


Le scoring de l'état de santé, c'était quand même cool :
http://www.mef-calaisis.fr/wp-content/uploads/2015/01/Focus-n-19-4eme-Campagne-de-prospection-de-la-plateforme-ICAME.pdf

**Comment by LucienMLD** [comment]
On pourrait regrouper : 
- Nb de besoins transmis - par région
- Nb de besoins sans réponse (que des refus) - par région
- Nb de besoins clôturés (dont 1 MER clôturée)

Mais il  nous faut un statut sur le besoin

**Comment by LucienMLD** [comment]
Passer le delai de 7 à 5 jours

**Comment by LucienMLD** [comment]
Changer le datepicker pour un qui fonctionne sur tout les navigateurs

**Comment by Adeline-Lrn** [comment]
On partirait sur un affichage séparé : 
- volet conseillé (indicateurs actuels à adapter, certains à enlever). 
- volet numérique
- total

**Comment by LucienMLD** [comment]
https://docs.google.com/document/d/1TqFwK0GGhyqTyXXCghB1JCnL98R6MIrEDr_36kSW6I8/edit

**Comment by LucienMLD** [comment]
Séparation de cette issue en plusieurs : #1502, #1503, #1505, #1506, #1607
