### ISSUE TITLE
Envoyer un email de confirmation (personnalisé) aux sollicitations via widget

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1126]
Pour l'instant, on n'envoie pas de mail de confirmation aux sollicitations déposées via un widget embarqué dans un iframe sur un site partenaire, pour éviter de parler de “place des entreprises” à un utilisateur qui n'en a pas entendu parler.

Il faut un message du style 
> **%{partenaire}: Confirmation de votre message**
> %{partenaire} et Place des entreprises coopèrent pour trouver le bon interlocuteur pour répondre à votre besoin. Nous vous tenons au courant rapidement.

**Comment by Adeline-Lrn** [comment]
Séquence mails aux chefs d'entreprise : https://docs.google.com/document/d/1BgFwfCGnSP7KrHZa-orRmWqGwuahdeHEzsECl-em5qg/edit

**Comment by n-b** [comment]
Fait par 06253bde17f8736edddf6c33fcd4052f3e13a309, si je ne m'abuse
