### ISSUE TITLE
Ajouter une page /accessibilite

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1273]
Au-delà du fait d’être ou non accessible, il faut une page récapitulative pour respecter la réglementation.

**Comment by astranchet** [comment]
*TLDR : la mention "Accessibilité : non conforme" est obligatoire pour les sites du service public.*

Hello, vous pouvez commencer par afficher le niveau de conformité dans le [footer](https://github.com/betagouv/place-des-entreprises/blob/6800af340bd4ad50141b3bf5ff4c59bc28f85aa7/app/views/pages/_footer.haml) : 

![image](https://user-images.githubusercontent.com/1374389/111305763-a39a3080-8657-11eb-9b18-fa125c47033f.png)

On considère qu'un site est "non conforme" en terme d'accessibilité tant que le niveau de conformité au RGAA (Référentiel général d'accessibilité pour les administrations) est inconnu. Pour pouvoir afficher "partiellement conforme" ou "totalement conforme", il est nécessaire d'effectuer un audit auprès d'un cabinet d'expert qui mesurera le taux de conformité.

Dans un 2ème temps, vous pourrez vous occuper de la 2ème obligation légale : **mettre en ligne une déclaration d'accessibilité**. Voici quelques exemples : 
- [La page Accessibilité de signal.conso.gouv.fr](https://signal.conso.gouv.fr/accessibilite) qui affiche le score de l'audit
- [La page Accessibilité du site des Designers Transverses](https://design.incubateur.net/accessibility) qui indique que le site n'a pas encore été audité, mais rassure les utilisateurs concernés sur les mesures qui ont été prises.
- [Le générateur de déclaration d'accessibilité](https://betagouv.github.io/a11y-generateur-declaration/#create) pour obtenir un exemple de déclaration conforme en quelques clics.

Je reste à dispo si vous avez des questions :) Vous trouverez aussi plus d'infos sur le [Kit Accessibilité](https://doc.incubateur.net/design/ressources-design/kit-accessibilite) de la documentation design ou sur #domaine-accessibilité sur le Slack.
