### ISSUE TITLE
Redesign des fiches entreprises

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1278]
Design : https://www.figma.com/file/lHjsPTxc5WocZJA6qYvmq5/Place-des-entreprises-Version-TEST-Copy?node-id=4097%3A658
(archives :  https://www.figma.com/file/kmfRJesNpCdj4goRrvVLKA/Place-des-entreprises?node-id=4097%3A937)

---

En fait, on veut aller plus loin que ça: nous ne faisons plus d’“analyse 360”, et la plupart des analyses n’ont qu’un seul besoin. On peut alors remplacer la fiche analyse par une “fiche besoin”, quitte à afficher les “autres besoins associés”. Ça permettrait de mettre aussi les autres analyses de la même entreprises.

Côté design, ça veut dire qu’il n’est plus nécessaire de mettre plusieurs sections de besoins; il n’y a plus qu’une seule section commentaires, etc.

---

* [x] Un point de refactor important concerne NeedsController, qui est utilisé actuellement pour afficher les analyses terminées à la place de DiagnosesController. Par exemple, `/analyses/1234` correspond à un Diagnosis en cours (et redirige vers l’étape courante, par exemple `/analyses/1234/visite`) tandis que `/besoins/1234` correspond au même Diagnosis, mais terminé.
* [x] Fil d'ariane
* [x] Js boutons fonctionnel
* [x] réparation tooltip
* [x] Mise à jour layout général : menu + fond gris
* [x] Page listant les autres besoins à faire : expert voit tous ses besoins, un admin voit tout
* [x] bug sur needs/_match_action  si on vient de créer une analyse à la mano

**Comment by n-b** [comment]
Voir aussi #613 et #621, ainsi que #1252

**Comment by Adeline-Lrn** [comment]
Pour les éléments non visibles sur la maquette et nos échanges sur peut-être des améliorations auxquelles on n'aurait pas pensé... https://docs.google.com/document/d/1ga5zzI-A5UYu-gfqbBIMZuN-OOggJnvrYCEjudRNd60/edit
