### ISSUE TITLE
Renommer “Mettre en échec” un besoin en “Archiver”.

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1286]
“Mettre en échec” implique que les mises en relation n’ont pas été prises en charge ou refusées; si un partenaire a répondu mais constaté qu’aucune aide n’était possible, il n’est pas forcément nécessaire de relancer les autres partenaires. Dans ce cas, on veut juste archiver le besoin pour ne plus en entendre parler.

Il y a aussi la notion de “partenaire prioritaire”, par exemple Pole Emploi sur le recrutement: si PE a contacté l’entreprise et clôturé en précisant qu’il n’y avait pas d’aide, il n’est pas utile de relancer les autres partenaires.

Ça a aussi des implications sur le calcul des stats.

**Comment by LucienMLD** [comment]
https://github.com/betagouv/place-des-entreprises/issues/1290 pour la notion de partenaire prioritaire
