### ISSUE TITLE
Redesign du formulaire de sollicitation

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1287]
Design sur 
https://www.figma.com/file/kmfRJesNpCdj4goRrvVLKA/Place-des-entreprises?node-id=833%3A90 mais on va probablement faire plus simple:

Design en une seule colonne:
* remonter les exemples d’accompagnements au dessus du formulaire (voire même au dessus du fil d’ariane)
* mettre le message d’aide pour la saisie de la description juste au dessus du champ de texte en question. (tout simplement, au lieu de le mettre sur la droite dans une popup animée)

**Comment by LucienMLD** [comment]
closed #1298
