### ISSUE TITLE
Corriger le décompte des relances

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1321]
@Tibo-aplus :
> ya marqué 17 besoins abandonnées alors qu'il y en a que 6. Pourquoi ?
> Le decompte des relances abandonnées n'est pas bon

Dans /relances, les décomptes n’ont pas l’air d’être correctement calculés. Je reproduis en local:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/139391/95862992-ed5ab400-0d63-11eb-8aa0-65f2c2b8b8b1.png">

J’avais alors 8 besoins à traiter, et 38 abandonnés. Ce n’est pas un problème de cache (il est désactivé), peut-être qu’il manque un `.distinct` dans une query?

**Comment by LucienMLD** [comment]
En fait ça comptait les analyses non terminées
