### ISSUE TITLE
Permettre de créer une analyse manuelle avec le nom de la ville

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#1325]
@stephreso:
> Lorsqu’on crée une analyse manuelle (sans siret), il faut connaître le code postal pour préciser la localisation. Ça serait bien de pouvoir renseigner la ville plutôt que le code postal que nous ne connaissons pas.

C’est en fait assez facile: l’api adresse que nous utilisons permet en fait de rechercher par nom, c’est nous qui filtrons le format de code postal. 

En local, en désactivant le pattern dans `_insee_code_fields.html.haml`, j’arrive à ça:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/139391/95871855-6f4fda80-0d6e-11eb-8996-8b9f016881e7.png">

On peut sans doute se contenter de changer un peu la taille des champs et de les renommer.

**Comment by stephreso** [comment]
l'essentiel pour moi est de pouvoir indiquer le nom d'une ville comme entrée. L'affichage me partait déjà très bien

**Comment by clairezed** [comment]
Réglé avec https://github.com/betagouv/place-des-entreprises/pull/1491 ?
