### ISSUE TITLE
Inclure les colonnes de l’équipe à l’export CSV

### ISSUE THREAD

**Issue by stephreso** [betagouv/place-des-entreprises#1327]
Lorsque plusieurs utilisateurs sont liés à un référent, ils apparaissent dans le tableau avec les sujets du référents auquel ils sont lié.
Si eux même ont des sujets en propre, cela crée une ligne supplémentaire par rapport à la ligne de leur compte référent.
--> les utilisateurs liés à un référent ne devraient pas apparaitre dans ce tableau comme étant en charge des sujets du référent auquel ils sont liés

**Comment by n-b** [comment]
En fait, la confusion vient d’un bug à l’export des CSV: il manque les colonnes email/nom/role de l’équipe. (depuis #1302)
