### ISSUE TITLE
Echec de jobs -> à régler ?

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#1334]
@LucienMLD @n-b je vois qu'il y a une dizaine de jobs depuis début octobre qui ont échoué https://place-des-entreprises.beta.gouv.fr/admin/jobs

C'est normal ? C'est un problème ? C'est à investiguer ?

**Comment by n-b** [comment]
Oui et non, c’est normal que des erreurs arrivent, c’est pour ça qu’on a de quoi les observer :p

Plus concrètement:
* [x] CompanyMailerService.send_satisfaction_emails undefined method `not_satisfaction_email_sent`, c’était le premier point de #1282, c’est réglé.
* [ ] `SMTP To address may not be blank`: Je croyais que ça arrivait quand on essayait d’envoyer des emails de suivi à des utilisateurs supprimés (enfin, soft-delete) entretemps. On a du rater un truc, mais à la limite c’est pas très grave. On peut juste éviter que mailjet ne se plaigne.
* [ ] Les deux plus récents m’inquiètent un peu: `uninitialized constant Delayed::Plugins::Raven::Utils` c’est pas normal du tout. Raven, c’est le plugin sentry, mais normalement, il est bien activé sur les jobs, la preuve juste en dessous.

**Comment by n-b** [comment]
Le troisième point est un bug de raven https://github.com/getsentry/sentry-ruby/issues/1041.  
Le fix est déjà mergé, prévu pour la prochaine release 3.1.2. (on est en 3.1.1)

**Comment by n-b** [comment]
Ça a l’air d’être réglé. Pour sentry-raven/sentry-ruby, cf #1510
