### ISSUE TITLE
Relances: 3/ Ajouter un système de boutons sur les fiches

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#1382]
Relances: 3/ Pour tout l'onglet Relances, associer un système de boutons sur les fiches comme dans Sollicitations pour faire sortir la fiche ( « Sortir de la relance »).

Paniers de besoins:
1. À relancer (par commentaire dans PDE) (7 jours)
1 bis. (invisible) Relancés
2. À rappeler (14 jours)
2 bis. (invisible) Rappelés
3. Prévenir l’institution (21 jours)
3 bis. (invisible) Institution rappelée.
4. À abandonner (30 jours). 

En plus il y a l’onglet “Besoins refusés” #1384

**Comment by n-b** [comment]
Techniquement, c’est probablement un nouvelle colonne `status_reminder` sur les Need. Au passage, on peut sans doute simplifier une grosse partie des scopes de Need avec une vraie colonne `status`, plutôt que de le calculer en fonction des match.
