### ISSUE TITLE
Relances: 4/ Ajouter un système de tags et de commentaires

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#1383]
Relances: 4/ Pour tout l'onglet Relances, associer un système de tags des fiches et de commentaires, comme ce qui existe déjà dans Sollicitations.

Pour l’instant, on a des commentaires au niveau des besoins, qui servent à la discussion entre experts.

Ici, c’est uniquement visible par l’équipe support. On pourrait les mettre au niveau du Diagnosis.

**Comment by clairezed** [comment]
Questions : 
- feedback lié aux `needs` plutôt qu'au `diagnosis` j'ai l'impression. L'appeler `personal_feedback` ?
- doit être visible par qui ? comment est-ce qu'on restraint la vision ? déjà implémenté ailleurs ? (vois rien dans `FeedbackPolicy`)
