### ISSUE TITLE
Permettre aux experts de retrouver un besoin clôturé par d'autres

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#1417]
Statut du besoin : Lorsqu'un besoin est clôturé par un expert, les autres experts ne le voient plus les besoins dans Demandes reçues. Ils appellent suite aux mails de notification car ils ne comprennent pas.

--
GV

Cf https://place-des-entreprises.beta.gouv.fr/admin/users/488 : ne voit pas le besoin https://place-des-entreprises.beta.gouv.fr/besoins/4782 ni celui ci https://place-des-entreprises.beta.gouv.fr/besoins/4917 ni https://place-des-entreprises.beta.gouv.fr/besoins/4870
ne voit pas les besoins qui sont clôturés car "pas d'aide disponible" ou entreprise non joignable"

**Comment by n-b** [comment]
dup #1323
