### ISSUE TITLE
Evolution stats publique

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#1480]
- [x] ajouter un graphique "pourcentage des demandes déposées dans les régions déployées", après le premier graphique
- [x] corriger le chiffre "total" pour les besoins d’entreprises transmis ayant donné lieu à un échange
- [x] supprimer la limite de 30 jours (`archived: true`) pour les besoins d’entreprises transmis ayant donné lieu à un échange
- [x] vérifier le nombre de demandes numériques ayant + d'un besoin, pour voir si la simplification peut être simple

**Comment by LucienMLD** [comment]
Depuis le 1er aout on a 674 analyses avec un seul besoin et 38 avec plusieurs, soit 5% environ.
Si on compte que le volet numérique 636 et 24 soit presque 6%
