### ISSUE TITLE
Bug de correspondance des chiffres dans les relances par referent

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#1487]
- Pb correspondances référents : 
 <img width="1218" alt="Capture d’écran 2021-01-07 à 11 28 24" src="https://user-images.githubusercontent.com/22002486/103882074-94d55180-50db-11eb-92bb-c2ed6e21cfdf.png">
 
- le nombre de "abandonnés" en hauts de france : affiché 17, en réalité 8

**Comment by clairezed** [comment]
@LucienMLD sur le problème "le nombre de "abandonnés" en hauts de france : affiché 17, en réalité 8", ce que je détecte : 
- on a effectivement 17 besoins
- par contre, on n'a bien moins de `Diagnosis.completed.where(needs: received_needs)`
- on repasse à 17 si on prend tout Diagnosis cumulé (pas uniquement les `completed`), ce qui n'a pas de sens.

=> ça sent les vieux needs moisis qu'il faut archiver, non ?

Il me semble que tu as déjà mené des campagnes d'archivage ? Tu saurais m'indiquer les commits, que je me calque sur toi ?

**Comment by clairezed** [comment]
Pour les repérer : `Need.reminders_to(:archive).joins(:diagnosis).merge(Diagnosis.in_progress)`
Mais on risque d'en avoir d'autres, peu à peu, non ? On fait quoi de tous les besoins qui sont liés à des Diagnostic `in_progress` ?
