### ISSUE TITLE
Prépa tests intrusion

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#1600]
- [x] mise en place plateforme iso-prod
- [x] mêmes données (@LucienMLD ?)
- [x] envoi email réorienté vers pascal (+ autre éventuellement) -> je l'avais fait, je peux m'en charger (pascal.schenkel@finances.gouv.fr & florian.camus-martin@finances.gouv.fr)
- [x] donner accès aux logs -> ouvrir accès scalingo à pascal.schenkel@finances.gouv.fr (@LucienMLD ?)
- [x] 2 comptes admin -> demander à Pascal les emails
- [x] 2 comptes conseillers -> demander à Pascal les emails
- [x] lien code source -> à envoyer à Pascal

**Comment by clairezed** [comment]
@LucienMLD ici, il reste du boulot, mais ça peut attendre le début de semaine prochaine. 
Ce que tu peux éventuellement faire -> voir quand tu es mentionné + haut :)
Je me charge de tout ce qui nécessite contact direct avec Pascal (j'essaye de lui écrire dans la semaine)

**Comment by LucienMLD** [comment]
J'ai pas compris "mêmes données (@LucienMLD ?)"

**Comment by clairezed** [comment]
@LucienMLD pour info, il s'agissait de l'import des données de prod sur la BDD intrusion, mais comme je m'étais planté dans mes copier-coller de variables d'env, l'appli intrusion affichait les données de staging. Ce qui effectivement laissait à penser que les données étaient déjà importées.

C'est rétabli hein
