### ISSUE TITLE
Pb demande refusé n'apparaissant pas dans les demandes refusées

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#1719]
Cette demande https://place-des-entreprises.beta.gouv.fr/besoins/12302 refusée par "Pole Emploi sauf 94" n'est pas dans leur panier refusé (quand je me met à la place de J. D.) . Il y a 9 demandes refusée mais pas celle de l'entreprise W****

**Comment by clairezed** [comment]
Le besoins est archivé, quand les besoins son archivés ils sont évacués des paniers sauf de “expiré” (edited)

**Comment by LucienMLD** [comment]
Il n'apparait pas parce qu'il est archivé et dans les onglets "boite de réception", "prise en charge", "cloturés" et "refusées" on enlève les besoins qui sont archivés pour éviter que les référents se retrouvent avec une pile de vieux besoins

**Comment by LucienMLD** [comment]
Ah on écrit le même commentaire en même temps 😄

**Comment by clairezed** [comment]
Ton commentaire à toi est mieux, j'ai juste fait un bête copier-coller
