### ISSUE TITLE
Amélioration import

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#1797]
### Souplesse de la saisie
- #1841 
- #1847 
- #1843
- #1849 
- #1852 
- #1845

### Amélioration des données
- (suppression du champ de fonction équipe (inutile))
- #1854
- #1859
- #1887
- #1857
-  #1860 

### Design annuaire
- #1764
- #1886

### Export
- possibilité de télécharger un fichier pour chaque institution avec seulement les sujets de l'institution (et leur description si possible ?) - fichier vierge pour nouveau déploiement. Y intégrer les descriptions spécifiques aux institutions, pour aider la saisie
- Lors de l'export de l'annuaire, supprimer les sujets où l'institution n'est pas positionnée dans notre annuaire.
- > permettre l'import / export de fichier xls (ajouter / supprimer les fichiers d'entête, ajouter de la mise en page, etc)

### Email responsable d'antenne 
- #1896 
- discuter avec l'équipe du mode de saisie (csv à importer ?). Fichier actuel : https://docs.google.com/spreadsheets/d/1YtR30jH1Llvj0Befwke9rKiPdgoYOlc7wdOYRf8m-wU/edit#gid=429242379. "C'est plutôt au fil des imports des antennes qu'on attribue un responsable."
- afficher dans l'annuaire (pour mise à jour référencement)
- afficher dans les relances (personne appelée à J+21))

### Mise à jour référencement via import
- #1856 

### A discuter
- Version ++ : avoir une pré-validation et/ou permettre de modifier à la volée les champs comportant des erreurs (un email, une antenne... avec suggestion d'antennes dont le nom est proche)

**Comment by Adeline-Lrn** [comment]
BONUS important : modification de sujets : quand le conseiller existe déjà en base, remplacer l’ancien sujet par le nouveau sujet indiqué par le partenaire dans le fichier excel.

**Comment by Adeline-Lrn** [comment]
Lors de l'export de l'annuaire, supprimer les sujets où l'institution n'est pas positionnée dans notre annuaire.
