### ISSUE TITLE
MAILS ENTREPRISE - Amélioration de la séquence mails à l'entreprise. 

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#1907]
1. Modification du contenu existant. 
2. Nouveau mail quand l'entreprise est injoignable (clôture par conseiller avec Injoignable). 
3. Automatisation du mail de relance. https://docs.google.com/document/d/1BgFwfCGnSP7KrHZa-orRmWqGwuahdeHEzsECl-em5qg/edit

**Comment by Adeline-Lrn** [comment]
@Lucien Merci beaucoup d'avoir mis les visuels, c'est bien plus facile pour se rendre compte de ce que ça donne !

- Il manque juste un point dans le premier mail. 
- Sinon je me disais qu'on peut mettre le nom de l'iframe en gras dans le mail de confirmation pour qu'il fasse le lien malgré l'univers graphique différent. 
- Le nom de l'entreprise lui peut apparaitre en italique pour le distinguer du reste du texte, y compris dans le mail de satisfaction et de relance (pour qu'ils soient uniformes). 
- Pour le mail de rétention, on pourrait mettre un bouton comme pour LinkedIn, ça rend pas mal du tout ! Et c'est plus tentant je trouve pour l'utilisateur. 
- La dernière question : est-ce qu'on peut mettre un lien de tracking identique dans tous les mails sauf rétention à « L'équipe Place des Entreprises » et un autre dans le bouton pour le mail de rétention ? 
Lien de tracking pour la séquence mail : https://place-des-entreprises.beta.gouv.fr/?pk_campaign=retention&pk_kwd=sequence-mail-pde
Lien de tracking pour le dernier mail rétention dans le bouton : https://place-des-entreprises.beta.gouv.fr/?pk_campaign=retention&pk_kwd=mail-retention
