### ISSUE TITLE
CHANTIER FUSION DES EXPORTS

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#1958]
- Fusionner les fichiers d'export des sollicitations et des mises en relation en un seul « big fichier » pour analyser l'ensemble d'un parcours : https://docs.google.com/document/d/1di6H11DOfkPX3yY0WHRxuDIHheaAvdIVg0uvBm4lmv4/edit
  - [x] pouvoir filtrer les MER par date de création des sollicitations 
  - [x] Ordonner par date de dépôt de demande, les plus récentes d'abord
  - [x] Utiliser `solicitation.provenance_categories` dans l'affichage des sollicitations

**Comment by Adeline-Lrn** [comment]
Optimisations après revue du fichier colonne par colonne : 

1. « date de sollicitation » plutôt que demande pour qu'on utilise la même terminologie ; 
2. « sujet choisi sur le site » plutôt qu'option ; 
3.  Le N° du code NAF serait plus pertinent selon Mathieu que l'intitulé pour faire des stats en regroupant certains secteurs... sur les fiches, on affiche uniquement l'intitulé, mais est-ce qu'on stocke le numéro quelque part ? 
4. Dans la colonne relecture des sollicitations, qu'est-ce que ça signifie « reçue » ? ou quand c'est vide ? On les clôture quand elles sont mises en relation, ou bien on clique sur Relancer quand on a fait un mail. Ça donne quoi dans le fichier ? Reçue (on n'a rien fait) / Cloturée / Relancée / Annulée ? 
5. Après la mise en relation, on bascule sur un nouvel objet donc on peut parler de besoin, de « date de transmission du besoin »
6. On peut basculer les colonnes relatives aux sources (GA, iframe etc) vers le début du fichier, juste après les descriptions des sollicitations pour avoir les étapes dans l'ordre ; 
7. La date de prise en charge devient la « date d'intervention » pour prendre tous les cas (prise en charge ou refus) ;
8. La date de clôture devient la « date de clôture de la prise en charge » juste à côté de la date d'intervention pour se souvenir qu'on se situe au niveau de la mise en relation et non du besoin. 

Question : On n'a pas de numéro d'identifiant de besoin aujourd'hui ? Juste des sollicitations puis des MER en principe ? Dans quel mesure c'est compliqué d'en créer un ? Peut-être avec le début des mêmes chiffes que la sollicitation ? 

Grosse question : Mathieu pense pour que le fichier des sollicitations, ce serait l'idéal de tout avoir cad toutes les colonnes évoquées avec les sollicitations non mises en relation dont les bout de lignes resteraient vides. Est-ce que ça va nous faire un export trop gros ?

**Comment by clairezed** [comment]
> « sujet choisi sur le site » plutôt qu'option ;

Là, vous voulez voir affiché les sujets (https://place-des-entreprises.beta.gouv.fr/admin/subjects) ou les landing subjects (accessibles là https://place-des-entreprises.beta.gouv.fr/admin/landing_themes) ? Le terme "option" m'avait fait afficher les landing subjects, mais le changement de terme me fait me poser la question.

> Le N° du code NAF serait plus pertinent selon Mathieu que l'intitulé pour faire des stats en regroupant certains secteurs... sur les fiches, on affiche uniquement l'intitulé, mais est-ce qu'on stocke le numéro quelque part ?

Pour le NAF, on a le code 'level2' (01, 02, 03...) ou bien le code 'a10' (AZ, BE, FZ...). Vous voulez lequel ?

> Dans la colonne relecture des sollicitations, qu'est-ce que ça signifie « reçue » ? ou quand c'est vide ? On les clôture quand elles sont mises en relation, ou bien on clique sur Relancer quand on a fait un mail. Ça donne quoi dans le fichier ? Reçue (on n'a rien fait) / Cloturée / Relancée / Annulée ?

- **Reçue** (`in_progress`) : état par défaut  des solicitations. Elles ont toutes ce statut là quand elles arrivent ici https://place-des-entreprises.beta.gouv.fr/sollicitations
- **Clôturée** (`processed`) : quand il y a eu MER ou bien quand vous cliquez sur Clôturer dans les options de la solicitations 
- **Relancée** (`reminded`) : quand vous cliquez sur Relancer dans les options de la solicitations (ce que vous faites logiquement après avoir envoyé un mail à l'Ets) 
- **Annulée** (`canceled`) : quand vous cliquez sur Annuler dans les options de la solicitations 
- Vide : ça, logiquement y'en a pas. Y'en avait dans le fichier ? C'est pas normal et ça doit être un pbde traduction (en BDD, toutes les solicitations ont un statut)

> On n'a pas de numéro d'identifiant de besoin aujourd'hui ? Juste des sollicitations puis des MER en principe ? Dans quel mesure c'est compliqué d'en créer un ? Peut-être avec le début des mêmes chiffes que la sollicitation ?

Si si, on a :) comme c'était pas demandé, je l'avais pas mis. Je le mets avant la "date de transmission du besoin" ?

> Grosse question : Mathieu pense pour que le fichier des sollicitations, ce serait l'idéal de tout avoir cad toutes les colonnes évoquées avec les sollicitations non mises en relation dont les bout de lignes resteraient vides. Est-ce que ça va nous faire un export trop gros ?

Ok, on peut faire ça ! On va basculer sur le même système que les MER avec envoi par mail. Et si ça bloque, ce sera l'occasion d'améliorer le système (ça dépendra beaucoup du nombre de solicitations que vous souhaitez récupérer -> "solicitation sur un mois", c'est moins lourd que "toutes les solicitations depuis le début")

**Comment by Adeline-Lrn** [comment]
> > « sujet choisi sur le site » plutôt qu'option ;
> 
> Là, vous voulez voir affiché les sujets (https://place-des-entreprises.beta.gouv.fr/admin/subjects) ou les landing subjects (accessibles là https://place-des-entreprises.beta.gouv.fr/admin/landing_themes) ? Le terme "option" m'avait fait afficher les landing subjects, mais le changement de terme me fait me poser la question.
> 
Oui c'est bien les landings subjects ! Comme ça on pourra mesurer le taux de correction/ le décalage entre ce que les chefs d'entreprise choisissent sur le site et les sujets réels des mises en relation (signe que le contenu doit peut-être être retravaillé par qu'ils voient plutôt telle problématique dans tel sujet que tel autre...)

> > Le N° du code NAF serait plus pertinent selon Mathieu que l'intitulé pour faire des stats en regroupant certains secteurs... sur les fiches, on affiche uniquement l'intitulé, mais est-ce qu'on stocke le numéro quelque part ?
> 
> Pour le NAF, on a le code 'level2' (01, 02, 03...) ou bien le code 'a10' (AZ, BE, FZ...). Vous voulez lequel ?
> 
Mathieu - Monsieur Stats, il maîtrise bien le sujet - cherche à avoir des codes Naf du type « 0111Z » soit 4 chiffres et une lettre. À partir de ça on peut tout faire en terme de stats sur les secteurs d'activités. 

> > Dans la colonne relecture des sollicitations, qu'est-ce que ça signifie « reçue » ? ou quand c'est vide ? On les clôture quand elles sont mises en relation, ou bien on clique sur Relancer quand on a fait un mail. Ça donne quoi dans le fichier ? Reçue (on n'a rien fait) / Cloturée / Relancée / Annulée ?
> 
> * **Reçue** (`in_progress`) : état par défaut  des solicitations. Elles ont toutes ce statut là quand elles arrivent ici https://place-des-entreprises.beta.gouv.fr/sollicitations
> * **Clôturée** (`processed`) : quand il y a eu MER ou bien quand vous cliquez sur Clôturer dans les options de la solicitations
> * **Relancée** (`reminded`) : quand vous cliquez sur Relancer dans les options de la solicitations (ce que vous faites logiquement après avoir envoyé un mail à l'Ets)
> * **Annulée** (`canceled`) : quand vous cliquez sur Annuler dans les options de la solicitations
> * Vide : ça, logiquement y'en a pas. Y'en avait dans le fichier ? C'est pas normal et ça doit être un pbde traduction (en BDD, toutes les solicitations ont un statut)
> 
Merci beaucoup, c'est très clair !

> > On n'a pas de numéro d'identifiant de besoin aujourd'hui ? Juste des sollicitations puis des MER en principe ? Dans quel mesure c'est compliqué d'en créer un ? Peut-être avec le début des mêmes chiffes que la sollicitation ?
> 
> Si si, on a :) comme c'était pas demandé, je l'avais pas mis. Je le mets avant la "date de transmission du besoin" ?
> 
Oui carrément, c'est parfait alors. 

> > Grosse question : Mathieu pense pour que le fichier des sollicitations, ce serait l'idéal de tout avoir cad toutes les colonnes évoquées avec les sollicitations non mises en relation dont les bout de lignes resteraient vides. Est-ce que ça va nous faire un export trop gros ?
> 
> Ok, on peut faire ça ! On va basculer sur le même système que les MER avec envoi par mail. Et si ça bloque, ce sera l'occasion d'améliorer le système (ça dépendra beaucoup du nombre de solicitations que vous souhaitez récupérer -> "solicitation sur un mois", c'est moins lourd que "toutes les solicitations depuis le début")

Super ! Nico va l'utiliser sur le mois pour les analyses acquisition. Moi c'est plus des analyses sur 6 mois ou un an et Mathieu aussi pour les partenaires. Potentiellement Ludivine aussi au niveau régional. Dans les protocoles c'est ce qui est prévu, leur donner les éléments de base (on est allé bien plus loin) tous les 6 mois/ un an.
