### ISSUE TITLE
Passer à rails 7.0

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#2166]
Pour l'instant certaines Gems ne sont pas compatibles Rails 7:

- [x] annotate - https://rubygems.org/gems/annotate
- [x] delayed_job_active_record - https://rubygems.org/gems/delayed_job_active_record
- [x] rails-i18n - https://rubygems.org/gems/rails-i18n
- [x] activeadmin - https://rubygems.org/gems/activeadmin
- [x] delayed_job - https://rubygems.org/gems/delayed_job

**Comment by clairezed** [comment]
Ca m'a l'air tout bon, on va pouvoir updater
