### ISSUE TITLE
bug dans les stats quand on sélectionne DILA et API on ne voit pas de demandes

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#2999]

**Comment by LucienMLD** [comment]
Le filtre institution des stats est fait pour trier les besoins reçues par cette institution, la DILA ne reçoit pas de besoins, donc c'est normal que ça affiche 0

**Comment by clairezed** [comment]
bon, je vois que tu l'as pris en compte, en fait :grimacing:

**Comment by LucienMLD** [comment]
closed by #3000
