### ISSUE TITLE
V2 des fichiers stats

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#3074]
https://docs.google.com/document/d/1Rjg7RkGy80ZOr5SgP5m0vgH6od9SN-YhmWMzhgceyhY/edit

- [x] Ajout d’un onglet de stats annuelles par région ou par antenne
- [x] Ajout dans les onglets stats trimestrielles et annuelles par région ou par antenne d’une colonne de % de répartition des besoins
- [x] Ajout d’un onglet de stats trimestrielles par sujet 
- [x] Ajout d’un onglet de stats annuelles par sujet 
- [x] Ajout d’un onglet « Repères nationaux » pour les fichiers non nationaux
- [x] Modification de l'onglet principal
- [x] Actualisation des termes dans l’onglet « Aide à la lecture »

**Comment by clairezed** [comment]
Ici, quels sont les points finalement à vérifier ?

**Comment by LucienMLD** [comment]
Tous, j'ai supprimé le point sur le passage au mensuel

**Comment by LucienMLD** [comment]
je viens de penser que le premier onglet j'ai supprimé les infos des colonnes de droite mais sans remettre en forme le titre etc. du coup il y a 3 colonnes vides
