### ISSUE TITLE
Retours UX DILA - site actuel

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#3258]
### Corrections globales

- [x] remplacer les composants home page tuiles -> card
- [x] comment ça marche -> remettre le "?" à côté de l'image
- [ ] espace interstitiel sur la vidéo : vérifier les réglages de tarteaucitron ?
- [x] Revoir formulaire newsletter : rajouter un label, texte d'aide au dessus...
- [x] Title Page accueil -> Accueil
- [x] Lien "autre sujet" cliquez-ici -> à remplacer par ????
- [x] E-mail -> email
- [x] Page connexion : Email professionnel nominatif / individuel ?
- [x] Cohérence nom lien / page Accès conseiller -> connexion conseiller
- [x] longueur ligne "Qui sont les conseillers" à réduire (idem ailleurs) (10 col max / ou max-width sur container)
- [x] nom@domaine.fr -> nom@example.fr
- [x] Tel : 06xxx / +33 xx
- [x] ex -> exemple
- [x] espacement des exemples et du champs à homogénéiser sur le formulaire
- [x] Form étape 3 : callout + icone
- [x] Je ne trouve pas mon entreprise -> ferré à gauche ? (comme "j'ai oublié mon mot de passe)
- [x] autofocus à enlever sur les champs du formulaire
- [x] rapatrier l'image "je donne mon avis"
- [x] revoir les ancrages du funnel

**Comment by Adeline-Lrn** [comment]
- l'ancrage à l'étape Siret ? 
- Présentation du service -> Dossier de presse 2022
- bouton explicite sur les vidéos pour les cookies désactivés
- espace Tuto à supprimer dans la partie publique quand on souhaite se connecter comme conseiller
- espacement des thèmes dans le footer sur la version mobile
