### ISSUE TITLE
Derniers (?) retours bascule

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#3415]
- [ ] Logo Aract à changer par Anact -> données à changer en prod au moment de la bascule, tout est prêt
- [x] L’adresse dpo@placedesentreprises.beta.gouv.fr dans la paragraphe RGPD des formulaires  = dpo@entreprises.service-public.fr ? 
- [ ] Dans « Je donne mon avis » en fin de parcours, confirmation de la demande envoyée, changer le nom du service au dernier moment = c’est @Mathieu qui a l’accès ? 
- [x] Sur la page de connexion conseillers, j’au une bande blanche avant le footer, vous aussi et est-ce voulu ?
- [x] Dans le tutoriel, il nous reste quelques termes « demande » à remplacer par « besoin » 
- [x]  Comme on est passé à une logique de besoins dans l’interface conseillers, on peut mettre la boite de réception au maxculin pluriel 
- [x] {Hors bascule} Le orange de la notification du nouveau besoin, est-ce qu’on ne peut pas l’adoucir un poil en reprenant celui qu’on utilise pour les équipes en poulets ? 
- [x] En tant que responsable national, j’ai changé l’antenne pour télécharger des stats locales et j’ai une erreur, est-ce que vous constatez un souci aussi ? 
- [x] Dans les mentions d'information, le nom du décret est bien un traitement dénommé Place des Entreprises, donc plutôt laisser le vrai nom du décret qui est sur Légifrance https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000045742996
- [x] Lien "En savoir plus" un peu + détaché ?
- [x] Le bouton de taille “LG” implique des espacements spécifiques : 18 px à gauche du l’icône / 8 px entre l’icône et le texte / 24 px à droite du texte
- [x] Bouton "Echanger..." aligné à gauche sur page d'accueil
- [x] Aérer l'interlignage des cartes thème / sujet (passer de 4px à 8 ou 12)
- [x] Aérer la liste des logos
- [x] Espacement de 32 px entre la dernière entrée du footer (liste des thèmes et la limite basse de l'encart gris)
- [x] Migration pour changer les mails équipe : @beta.gouv.fr -> @entreprises.service-public.fr

**Comment by LucienMLD** [comment]
Le orange des notifications est limite marron parce qu'aucun orange n'est accessible selon le RGAA
