### ISSUE TITLE
Ajout d’un `mtm_campaign` pour l’API de recherche d’entreprises

### ISSUE THREAD

**Issue by XavierJp** [betagouv/place-des-entreprises#3423]
Nous souhaiterions tracker plus finement les utilisations de notre API Recherche d’Entreprises. Pourriez-vous ajouter `mtm_campaign=place-des-entreprises` à la fin de l’url ?

https://github.com/betagouv/place-des-entreprises/blob/37ae70ebd72128d5b8402604163dcbaca2ccb22c/spec/services/api_recherche_entreprises/search/base_spec.rb#L8

Les stats apparaitront ici dans la partie `Campagne` :
https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=294&period=range&date=previous30#?period=day&date=2024-04-30&idSite=294&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll

**Comment by clairezed** [comment]
On a changé de nom !
Ca te va si on met `mtm_campaign=conseillers-entreprises` ?

**Comment by XavierJp** [comment]
Félicitations ! Bien sur c'est parfait
