### ISSUE TITLE
Gérer les compétences par institution

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#578]
Indiquer, pour chaque institution, les Sujets susceptibles d’être sélectionnés par les référents.
La description de chaque sujet correspond à la “compétence” de cette institution sur le sujet.

* Supprimer le lien “compétence” entre les référents et les sujets, (ça simplifie aussi l’algo de mise en relation)
* Les référents peuvent cocher / décocher les sujets auxquels ils répondent parmi ceux de l’institution.

---

Les experts membres d’une institution ne peuvent avoir de compétence que parmi celles de l’institution.

![IMG_2398](https://user-images.githubusercontent.com/139391/68124917-b8699e80-ff10-11e9-9683-195f2392cb21.jpg)

**Comment by n-b** [comment]
À vérifier en base: existe-t-il des référents de la même institution qui ont des compétences différentes sur le même sujet?

Si c’est le cas, on a peut être besoin de séparer des sujets en deux.

**Comment by LucienMLD** [comment]
- [ ] création des modèles InstitutionSubject et ExpertInstitutionSubject
- [ ] migrer les données de skills vers les nouveaux modèles (idempotent)
- [ ] créer page institution/:id/(subject?)
- [ ] changer la requète de match
- [ ] retirer skill
- [ ] page profil référent


![IMG_20191105_173815](https://user-images.githubusercontent.com/22002486/68287267-c17a7d00-0082-11ea-9c95-82dfca8e1423.jpg)


![IMG_20191105_173829](https://user-images.githubusercontent.com/22002486/68287274-c3dcd700-0082-11ea-9505-ff520e0e25f3.jpg)

**Comment by LucienMLD** [comment]
@n-b si on crée un page institution/:id il faudrait aussi une page index des institutions non ? Pour pouvoir accéder à la page sans devoir chercher l'id de l'institution. ou on met un lien directement depuis ActiveAdmin

**Comment by n-b** [comment]
Yes. Pour l’instant on a quelques dizaines d’institution, donc on peut tout afficher sur une seule page, peut-être qu’à un moment il faudra faire plus subtil.

Qui a accès à la page `/institutions`? Uniquement l’équipe support (nous) ou bien tous les utilisateurs inscrits? ou même tout le monde?
