### ISSUE TITLE
Permettre aux référents d’indiquer s’ils sont “spécialistes” d’un sujet ou “suppléants”

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#582]
Laisser les référents indiquer qu’ils sont spécialistes d’un sujet ou simplement suppléants (peuvent être contactés si aucun spécialiste n’est disponible) (suite à #581)

**Comment by LucienMLD** [comment]
On peut envisager la mise en place par plusieurs moyens dans le code :  
- un champ `specialist` dans la table `experts_subjects` en booléen
- un champ `supléant`   

et coté vue
- une checkbox 'Je suis spécialiste'
- une checkbox 'Je suis supléant'
- un radio button 'spécialiste vs supléant'

**Comment by n-b** [comment]
On peut aussi déclarer un enum `[:specialist, :fallback]` en base? C’est plus explicite qu’un booléen, et ça permet d’évoluer plus tard. Pour la UI, je suis plutôt partisan d’un radio button :)

**Comment by LucienMLD** [comment]
oui pour l'enum je ne l'ai jamais utilisé donc je n'y avait pas pensé

Je suis d'accord aussi pour le radio
