### ISSUE TITLE
Refactorer les états des besoins (« boutons »)

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#583]
Identification des problèmes : 

Prise en charge : pas d’appel systématique
Refuser : ne reflète pas la réalité et trop subjectif
Clôturer : notion floue
Différencier clôture du besoin et clôture de l’intervention du référent
Différencier clôture négative (pas de contact, pas de profil pour recrutement, pas d’accompagnement possible) et clôture positive

Premières pistes : 

- « Pas de réponse » devient « En attente de votre réponse »

- « Refuser » devient « Ce n’est pas de ma compétence » : Hors champs de compétence (version courte état).

- « Prendre en charge » devient « Prendre en charge et rappeler de l’entreprise »

- « Clôturer » devient « Clôturer mon accompagnement » 
Et là demander, une fenêtre s’ouvre avec cette question « Le besoin de l’entreprise est-il résolu selon vous ? 
	- Oui, il n’est plus utile que les autres référents interviennent. 
	- Non, je laisse les autres référents intervenir. 
	- Abandon (besoin déjà connu, situation trop complexe…)

![IMG_2399](https://user-images.githubusercontent.com/22002486/68125490-0a5ef400-ff12-11e9-8e81-11dbd8633a86.jpg)

**Comment by n-b** [comment]
Côté code, ça serait peut-être l’occasion de faire disparaitre `audited` qui est largement surdimensionné pour ce qu’on fait sur `Match#status`.

**Comment by n-b** [comment]
On a aussi envie de rapprocher les boutons de l’envoi de commentaire, un peu comme le bouton “Close and comment” de github. L’idée est de permettre d’indiquer son action et d’envoyer un commentaire en un seul clic; de l’autre côté, ça permet de n’envoyer qu’un seul email au conseiller.

**Comment by n-b** [comment]
État des réflexions à jour:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/139391/83884613-68bcb100-a745-11ea-8290-6c87629190aa.png">

**Comment by n-b** [comment]
Fait dans #1215
