### ISSUE TITLE
Mise en place d'un Blog / section aide / wordpress / gitbook

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#584]
Exemple : https://nrichand.github.io/impact-job/
Blog pour les chefs d'entreprises
MAJ : 1 à 2 fois par mois

Objectifs :
- Référencement naturel
- outil de com pour les Chefs d’entreprises
- Crédibiliser le site
- Outil de lobbying auprès des partenaires

**Comment by n-b** [comment]
à tester, netlify-cms?

**Comment by n-b** [comment]
À vue de nez, [netlify-cms](https://www.netlifycms.org/docs/add-to-your-site/) est _state of the art_, mais un peu complexe à mettre en place: il faut un repo git séparé pour éviter de mettre le bazar dans le code, et donc un domaine distinct.

Techniquement, on peut aussi tout garder en interne dans l'app, avec un engine rails. Il y a plusieurs gems qui font ça, par exemple [blogit](https://github.com/KatanaCode/blogit) ou [blogboi](https://github.com/charliereese/blog_boi) qui ont l’air à peu près maintenue. C’était clairement _cool en 2014_ mais ça reste le plus simple.

**Comment by n-b** [comment]
Maintenant qu’on gère le domaine nous-même, on peut très bien définir un sous-domaine genre `blog.<pde>` qui sert une autre app; en fait, AlwaysData permet même d’installer en deux clics un wordpress.

Par ailleurs, avec les buillpacks, on doit pouvoir configurer Scalingo pour servir ce sous-domaine sur `<pde>/blog`. (Techniquement, on utilise déjà setup “multi buildpacks” avec le fichier `.buildpacks`. Avec le [buildpack nginx](https://doc.scalingo.com/platform/deployment/buildpacks/nginx) on devrait pouvoir faire ce qu’on veut.)

**Comment by n-b** [comment]
C’est un peu plus complexe que ça via Scalingo: il faudrait une app en plus pour gérer le nginx, devant l’app rails et le blog. Des réponses du support de scalingo:

> Même si c'est possible via pas mal de choses complexes, il faut mieux voir que 1 process = 1 app. Or dans votre cas, il y a deux process à lancer (le rails et le nginx - et la vous lancez plus le rails). Donc le mieux est de garder votre app rails, et créer une autre app qui gère uniquement le ngnix (plutôt via un autre repo git d'ailleurs, même si tout mettre dans un est possible aussi)
> Le multi buildpack est la pour l'usage de plusieurs technologies dans un même container, pas de plusieurs core processus dans un container
> Malheureusement, avoir un reverse proxy dans un container indépendant semble être la solution la plus simple.
