### ISSUE TITLE
Fusionner la page connexion et la page information version conseillers

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#585]
https://place-des-entreprises.beta.gouv.fr/users/sign_in
&
https://place-des-entreprises.beta.gouv.fr/conseillers

#454

**Comment by n-b** [comment]
On peut rajouter un texte du style:

> Qui sont les conseillers utilisant Place des Entreprises ? 
>
> Les conseillers de Place des Entreprises sont des agents des organismes publics et parapublics chargés de la relation entreprise. Le service compte aujourd’hui plus de 900 conseillers au sein de 50 partenaires publics. 
>
> Chaque conseiller est référencé comme expert sur un champ de compétences précis. Le service lui permet de recevoir des besoins d’entreprises correspondant à son champ d’intervention et de partager des besoins relevant d’autres compétences. Le conseiller utilisant Place des Entreprises devient ainsi un interlocuteur privilégié pour les chefs d’entreprises : il accède en 2 minutes à tous les partenaires publics proposant une grande diversité d’accompagnements. 
>
> Si vous êtes agent d’un acteur public porteur de solutions, rejoignez-nous !
>
> Comment s’inscrire ? 
>
> Pour accéder au service, envoyez-nous un email à contact@place-des-entreprises.beta.gouv.fr.

**Comment by Adeline-Lrn** [comment]
Qui sont les conseillers utilisant Place des Entreprises ?

Les conseillers de Place des Entreprises sont des agents des organismes publics et parapublics chargés de la relation entreprise. Le service compte aujourd’hui plus de 900 conseillers au sein de 50 partenaires publics.

Chaque conseiller est référencé comme expert sur un champ de compétences précis. Le service lui permet de recevoir des besoins d’entreprises correspondant à son champ d’intervention et de partager des besoins relevant d’autres organismes. Le conseiller utilisant Place des Entreprises devient ainsi un interlocuteur privilégié pour les chefs d’entreprises : il accède en 2 minutes à tous les partenaires publics proposant une grande diversité d'accompagnements.

Si vous êtes agent d’un acteur public porteur de solutions, rejoignez-nous !

Comment s’inscrire ?

Pour accéder au service, envoyez-nous un email à contact@place-des-entreprises.beta.gouv.fr.
