### ISSUE TITLE
Améliorer “Qui sommes-nous?”

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#586]
* [ ] Ajouter une photo de l'équipe
* [x] Ajouter une rubrique en bas de page "On parle de nous" avec les liens vers les articles de presse.

**Comment by Adeline-Lrn** [comment]
https://docs.google.com/document/d/1g3GmpZMAo1yMsr9XmTZfyx1jZm1pFem5dallM8Bq3u0/edit
