### ISSUE TITLE
Permettre d’accéder aux analyses réalisées par les autres membres de son Antenne

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#588]
Il y a probablement quelques changement à faire pour que les commentaires soient correctement attribués, et que les emails n’indiquent pas le nom de l’`advisor` si c’est une action faite par un autre conseiller de l’antenne.

**Comment by LucienMLD** [comment]
@n-b Quels emails indiquent le nom de l'advisor actuellement ? Je n'en ai pas trouvé

**Comment by n-b** [comment]
Je pense principalement à `daily_change_update` et `match_feedback`, et pour clarifier, des action qui seraient attribués à l’expert contacté plutôt qu’au collège de la même antenne.

Il me semble qu’on a dit que n’importe qui pouvait ajouter un commentaire sur une analyse qui concerne son antenne, mais pas qu’un collègue non membre de l’équipe expert pouvait indiquer une prise en charge?
