### ISSUE TITLE
Ne pas afficher dans /relances les besoins relancés

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#591]
Quand l’équipe support ajoute un commentaire sur un besoin pour relancer un référent, ce besoin ne devrait plus être compté comme “sans nouvelles depuis 3 semaines”.

Il manque peut-être quelque chose dans le scope `no_activity_after`.

**Comment by n-b** [comment]
J’ai refait un test, ça m’a l’air de fonctionner normalement, quand je fais un commentaire sur les besoins abandonnés, ceux-ci ne sont plus marqués “en souffrance”. Peut-être que je ne regarde pas au bon endroit :/

**Comment by n-b** [comment]
Je ferme: entre #1097 et les autres changements sur `last_activity_at`, ce bug n’est de toute façon plus pertinent.
