### ISSUE TITLE
Partager facilement le lien de la fiche de visite

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#592]
Depuis l’onglet relance, sur la fiche d'un référent à relancer, quand on choisit un besoin on ne peut pas partager directement le lien vers la visite, par exemple pour lui envoyer.
* [x] Faire en sorte d’avoir des liens partageables. (cf la fin des access_token, #638)
* [ ] Partager un lien directement positionné sur le besoin qui nous intéresse

**Comment by n-b** [comment]
De fait, ça n’aura plus de sens après #1278
