### ISSUE TITLE
BPI FRANCE : Prérequis pour matcher avec le fonctionnement du service client

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#594]
Travaillé avec BPI France à une modalité de référencement national. 
En effet, le service client est centralisé sur Paris. Présence également de chargés d'affaires sur les régions. 
On mobilise sur leurs portails régionaux le service client sur Paris. C'est ensuite redispatché ou non en fonction du besoin.

On va devoir se coller à cette modalité centralisée. Nécessite qlq ajustements mais permettra un déploiement rapide concernant ce partenaire qui nous suit dans l'aventure. 
- bpi France va créer un mail type "pde@bpifrance.fr"
- on debranche M et H
- il faudrait le contenu de la visite dans le mail
- & possiblement les boutons.
(trop d'interface, des partages vers les chargés d'affaires, protection info...) 

BPI France s'engage à répondre à toutes les demandes. Si proposition à faire ou si rien à proposer.
On poussera des analyses sur le taux de conversion plus tard...
On se donne 3 mois pr tester avant la grande année 2020 ! L'équipe est super partante chez eux.

---

Modification envisagée: mettre le bouton de prise en charge directement dans le mail.

**Comment by n-b** [comment]
fermé pour #600
