### ISSUE TITLE
N’envoyer que les mails pertinents lors de l’inscription

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#596]
Pour la création des comptes utilisateurs, trois choses sont nécessaires avant connexion :
- valider que l’utilisateur/rice a le droit d’utiliser PdE
- confirmer qu’iel reçoit bien les emails envoyés par PdE
- lui faire choisir son mot de passe.

Il y deux scenarios:
1. inscription autonome depuis le formulaire `users/sign_up`
2. création de compte par les admin et invitation

---

1. Inscription autonome
 - Utilisateur: remplissage et envoi du formulaire, avec email et mdp
 - Serveur: envoi du mail de confirmation de l’email
 - Utilisateur: clic sur le lien de confirmation
 - Admin: si l’email n’est pas whitelistée, validation (ou non) du compte
  - Serveur: dans ce cas, envoi du mail de validation du compte
 - Une fois l’email confirmé et le compte validé:
  - Utilisateur: login

2. Création de compte par un(e) admin
 - Admin: création du compte, validé implicitement
 - Serveur: envoi du mail d’invitation pour choix du mot de passe
 - Utilisateur: clic sur le lien et changement de mot de passe
 - Utilisateur: login

---

Aujourd’hui, le scénario 2 ne se passe pas exactement comme ça: aucun mail n’est envoyé, l’utilisateur doit essayer de se connecter et demander une réinitialisation du mot de passe lui-même.

Il suffirait d’appeler user.send_reset_password_instructions, mais on ne veut pas utiliser comme premier mail d’invitation le même texte que le mail de réinitialisation du mot de passe.

**Comment by n-b** [comment]
Tout ça est a été fait dans #559 et suivantes.
