### ISSUE TITLE
Prévenir l’entreprise lors de la prise en charge

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#597]
Par transparence et pour du suivi de qualité.

* [x] Mail de confirmation lors de la création d'une sollicitation
* [x] Prévenir l’entreprise lors de la mise en relation
> « suite à votre rencontre avec […] votre besoin […] a bien été transmis à […]. Ce partenaire est susceptible de vous rappeler pour vous accompagner »

**Comment by n-b** [comment]
Pistes:

# Accusé de réception lors de la solicitation

> Bonjour,
> [Merci,]
> [récapitulatif de votre demande]
> [On vous rappelle pour clarifier si besoin est]
> [On prévient ensuite les interlocuteurs publics compétents sur votre territoire].

# Message envoyé automatiquement lors de la mise en relation

(en même temps que la notification des référents)

> Bonjour,
> L’équipe Place des entreprise a bien reçu votre demande et a prévenu (les/3) interlocuteurs publics compétents [sur votre territoire]. Ils devraient être rappelés par eux prochainement. Si vous êtes sans nouvelles d’ici trois semaines, n’hésitez pas à revenir vers nous.

# Message envoyé lors de la prise en charge

?

# Message envoyé lors de la clôture

?

# Message envoyé lors de l’échec

???

**Comment by LucienMLD** [comment]
closed by #597
