### ISSUE TITLE
Permettre d’aider les utilisateurs débutants

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#605]
Plusieurs pistes d’accompagnement:
* permettre à l’équipe PdE de suivre les référents qui recoivent une sollicitation pour la première fois
* identifier les conseillers qui font leur première analyse,
* savoir quels utilisateurs ont eu (ou pas) une formation directe.

**Comment by Tibo-aplus** [comment]
mettre ce lien , pour que les conseillers puisse à tout moment s'incrire à une des prochaines session de démo : https://app.livestorm.co/place-des-entreprises_
