### ISSUE TITLE
Filtrer les référents affichés par d’autres critères

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#606]
En plus des domaines de compétence et des zones d’intervention, filtrer les référents selon d’autres critères de type d’entreprises. (à préciser: artisanat vs commerce, spécificité zonale.)

Par exemple:

CRP : commissaire au redressement productif
(certains agents de la DIRECCTE)
Ne proposer la mise en relation avec les CRP que si la société a plus de 20 salariés
On peut le faire en dur pour le moment, et réfléchir à un système de règles plus tard.

CCIR :
Segmentation basée sur le code APE
Industrie / Services aux particuliers / services aux ets / commerce
2 référents se partage une compétence avec un cible ets préférentielle
https://docs.google.com/spreadsheets/d/1RwYDvsdOn_aZB6tf1luzc2QMj6tgHA621FYh8qt3s6U/edit?usp=drive_web&ouid=107066189680083059654

Filtrer par registre dans lequel l'entreprise est enregistrée
- inscrit au RCS -> CCI (https://data.inpi.fr/entreprises/824279483)
- inscrit au RM -> CMA (https://api-rnm.artisanat.fr/v2/entreprises/824279483)

**Comment by n-b** [comment]
Permettrait de nettoyer le référencement en hdf:
* Oise : Distinction Commerce/tourisme & industrie/services
* Amiens-Picardie : Distinction Commerce/tourisme & industrie/services

**Comment by n-b** [comment]
Retours utilisateurs:
* users/364
