### ISSUE TITLE
Réécrire les CGU

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#612]
@MathieuGens tu te souviens de cette issue? Il y avait un besoin particulier?

**Comment by MathieuGens** [comment]
https://place-des-entreprises.beta.gouv.fr/cgu
This? 
Tu as déjà fait une repasse visiblement.
On peut certainement compléter... Ces CGU concernent PDE ou juste l'accès conseiller?

**Comment by n-b** [comment]
On parle encore d’experimentation en HdF, et je ne crois pas qu’on ait vraiment écrit de paragraphe sur les sollicitation directes…

Cela dit, c’est plus une tâche de ton côté (ou @Adeline-Lrn ?) plus qu’une issue github, on peut fermer ici et vous laisser gérer ? 😁

**Comment by n-b** [comment]
(Je ferme ici)
