### ISSUE TITLE
Suivi aval: Reformuler les emails de notifications et de relance

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#614]
## Mail de relance:
Faire comprendre que le conseiller attend des nouvelles

“Faites savoir à david que vous avez pris en charge le besoin”
“Donnez à David (conseiller URSSAF) des nouvelles”

## Mail de notification
Mettre plus en valeur le fait que c’est un humain qui est à l’origine de la mise en relation.

---
La formulation des deux mails est à améliorer de toute façon.

**Comment by n-b** [comment]
Ça fait doublon avec #600. Autant ne garder que celui-ci.
