### ISSUE TITLE
Résoudre bug pole-emploi.net

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#615]
À vérifier lors du rdv DG Pôle emploi, si position forte, tenter d'utiliser le mail de l'équipe ets en. Net ou créer 1 mail dédié pôle emploi/pde. Fr
(objet ne plus passer par l'accueil)

**Comment by n-b** [comment]
C’est un vieux truc réglé depuis un bon moment. On n’utilise plus que les adresses `@pole-emploi.fr`, pas `@pole-emploi.net` que ce soit les adresses d’équipe ou individuelles.

**Comment by n-b** [comment]
(En contactant sur `pole-emploi.net`, ça rentre dans le système de gestion compliqué de PE, ce qu’on ne veut pas pour nos notifications)
