### ISSUE TITLE
Bug: affichage de doublons dans /admin/experts 

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#691]
par exemple en cherchant les experts de la CCI de Douai

**Comment by n-b** [comment]
(Fermé par erreur dans #693)
---
Je soupçonnais un bug lié à la mise à jour de rails 6, ou plus précisément à un [hack qui existait précédemment pour fixer ce bug](https://github.com/betagouv/place-des-entreprises/pull/654/files#diff-63527fd5b1414d50b77a9137ec2b2e31L296-L303), mais je n’arrive pas à reproduire non plus 🤔 

@stephreso tu saurais dire dans quel cas précisément tu as vu des doublons dans l’admin?

**Comment by n-b** [comment]
Exemple d’url:
`https://place-des-entreprises.beta.gouv.fr/admin/experts?q%5Bantenne_institution_id_eq%5D=15&q%5Bantenne_territories_id_eq%5D=55&q%5Bsubjects_id_eq%5D=39&commit=Filtrer&order=full_name_asc`
