### ISSUE TITLE
Ajustements sur la promesse sur la page d’accueil

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#779]
Brouillon:
![IMG_2623](https://user-images.githubusercontent.com/139391/72738078-15383500-3ba1-11ea-825a-0711fbdbce55.jpg)

**Comment by Adeline-Lrn** [comment]
Place des Entreprises : le guichet public d'accompagnement des TPE & PME / qui accompagne (bandeau bleu en haut). 

Logo
Juste en dessous la nouvelle promesse : 
TPE & PME, vous avez un projet, une difficulté, une question du quotidien ?
Service public simple et rapide : vous êtes rappelé par LE conseiller qui peut vous aider. 

CTA : Déposez votre demande

Un service du Ministère de l'Economie et du Ministère du Travail, avec plus de 50 partenaires publics : LOGOS

Catégories de sujets.

**Comment by Adeline-Lrn** [comment]
Page thématique : 

On garde la question thématique en enlevant « Patrons ». Juste TPE & PME, blabla. 
Juste en dessous : Service public simple et rapide : vous êtes rappelés par LE conseiller qui peut vous aider. 

CTA : Déposez votre demande

Un service du Ministère de l'Economie et du Ministère du Travail, en partenariat avec : LOGOS des partenaires concernés par la thématique. 

Exemples d'aides. 

Formulaire. 

On enlève le comment ça marche.
