### ISSUE TITLE
changer le logo CCI HDF

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#796]
![CCI-Hdf_page](https://user-images.githubusercontent.com/22002486/73371651-435ef880-42b6-11ea-9360-9fb56a4aed95.jpg)

**Comment by LucienMLD** [comment]
Pour l'instant les logos sont liés à l'institution, est-ce qu'il faut pourvoir le mettre au niveau de l'antenne pour avoir un logo différent suivant les régions ?

**Comment by n-b** [comment]
En fait, ça marche pour les Institutions et les Antennes qui ont `show_icon` à true.
