### ISSUE TITLE
Bug affichage header sur mobile

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#820]
Sur certains smartphone (Iphone 6) le header ne s'affiche pas correctement ... Le logo est coupé et les boutons sont à la ligne  ce qui prend beaucoup d'espace

**Comment by n-b** [comment]
iPhone X:
![IMG_8786CE4F26FC-1](https://user-images.githubusercontent.com/139391/74418870-5ee70900-4e49-11ea-9546-9acb475ef6ba.jpeg)

Android (modèle?): 
![Screenshot_20200213-001727](https://user-images.githubusercontent.com/139391/74419042-9c4b9680-4e49-11ea-81d4-fd4ecfa54475.png)
