### ISSUE TITLE
Améliorations page d'une analyse

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#872]
dans la fiche d'analyse, pour l'envoi d'un message :
mettre nouveau commentaire au lieu de message, 
quand on passe la souris sur le bouton envoyer il faudrait ouvrir une fenêtre avec un message précisant que ce commentaire n'est pas adressé au chef d'entreprise, pour transmettre l'information au dirigeant veuillez l'appeler

**Comment by n-b** [comment]
Done!
