### ISSUE TITLE
Clarifier le message de prise en charge par l'équipe PDE

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#877]
Changer le message de notification de prise en charge envoyé aux entreprises, dans le cas d’une prise en charge par l’équipe support **parce qu’aucun référent pertinent n'est disponible**.

1/ Au moment de la prise en charge par un expert :

> "Bonjour,
> Vous avez déposé une demande pour votre entreprise [nom de l'ets] sur le portail place-des-entreprises.beta.gouv.fr .
> Nous vous informons que votre demande - [sujet de la demande] - vient d'être prise en charge par [institution du référent].
> Un conseiller va prendre contact avec vous pour vous accompagner. Vérifier également vos mails.
> Bonne journée.
> L'équipe Place des Entreprises
> Si vous souhaitez retirer votre demande, contactez nous contact@place-des-entreprises.beta.gouv.fr"

2/ "Autres typologie de besoins", pris en charge par équipe support:

> Bonjour,
> Votre demande nécessite la recherche d'un nouveau conseiller. L'équipe Place des Entreprises s'active pour l'identifier au plus vite.
> Nous vous mettrons en relation avec le conseiller.
> Il prendra contact avec vous pour vous accompagner. Vérifier également vos mails.
> L’équipe Place des Entreprises.
> Si vous souhaitez retirer votre demande, contactez-nous contact@place-des-entreprises.beta.gouv.fr

**Comment by Adeline-Lrn** [comment]
Finalement on le supprimerait, séquence mails aux entreprises : https://docs.google.com/document/d/1BgFwfCGnSP7KrHZa-orRmWqGwuahdeHEzsECl-em5qg/edit

**Comment by LucienMLD** [comment]
on ne fera pas cet email, suite dans #1159
