### ISSUE TITLE
Ajustements design des landing pages

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/place-des-entreprises#939]
https://www.figma.com/proto/kmfRJesNpCdj4goRrvVLKA/Place-des-entreprises?node-id=1%3A4&viewport=378%2C588%2C0.42667731642723083&scaling=min-zoom

* les sections qui s’ouvrent et se ferment, c’est pas compliqué
* les ajustements de liste et les puces en emoji non plus
* le formulaire sur une autre page, avec le retrait des cases à cocher (l’option est présélectionnée en fonction du lien “sur ce formulaire) c’est plus compliqué, disons une ou deux journée de taf?

**Comment by n-b** [comment]
followup #970:
* voir si on supprime ou si on améliore les animations d’ouverture
* je me demande si on n’a pas supprimé quelques règles css en trop, le call-to-action sur la page d’accueil n’est plus en gras.

**Comment by n-b** [comment]
* Il y avait un lien “back” sur la page formulaire du figma, je me demande si c’est pertinent.
