### ISSUE TITLE
Ajuster le message de mise en relation après sollicitation ou widget

### ISSUE THREAD

**Issue by n-b** [betagouv/place-des-entreprises#968]
Dans les emails de mise en relation pour les analyses faites à partir de sollicitation, on dit toujours:
>  %{advisor_name_with_role} l’a rencontrée le %{visit_date}.

ce qui n’est pas pertinent dans la cas d’une sollicitation directe. 

Préférer quelque chose dans ce genre:

* dépot direct sur PDE :
  > la société a sollicité Place des entreprises le %{visit_date}

* dépot via un widget sur un site partenaire :
  > la société a sollicité Place des entreprises via le formulaire sur %{url_partenaire} le %{visit_date}
 
(extrait de #601)

**Comment by Adeline-Lrn** [comment]
Séquence de mails aux chefs d'entreprises : https://docs.google.com/document/d/1BgFwfCGnSP7KrHZa-orRmWqGwuahdeHEzsECl-em5qg/edit
